# Generated by Django 5.1.3 on 2025-01-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotheques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, db_column='Nom', null=True)),
                ('rue', models.TextField(blank=True, db_column='Rue', null=True)),
                ('commune', models.TextField(blank=True, db_column='Commune', null=True)),
                ('cp', models.IntegerField(blank=True, db_column='CP', null=True)),
                ('coordonnees_geo', models.TextField(blank=True, db_column='Coordonnees geo', null=True)),
                ('services_proposes', models.TextField(blank=True, db_column='Services proposes', null=True)),
                ('type_d_etablissement', models.TextField(blank=True, db_column='Type d etablissement', null=True)),
                ('heures_d_ouverture', models.TextField(blank=True, db_column='Heures d ouverture', null=True)),
                ('fermeture_annuelle', models.TextField(blank=True, db_column='Fermeture annuelle', null=True)),
                ('conditions_d_acces', models.TextField(blank=True, db_column='Conditions d acces', null=True)),
                ('site_web', models.TextField(blank=True, db_column='Site web', null=True)),
                ('telephone', models.TextField(blank=True, db_column='Telephone', null=True)),
            ],
            options={
                'db_table': 'bibliotheques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coworking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, db_column='NOM', null=True)),
                ('adresse', models.TextField(blank=True, db_column='ADRESSE', null=True)),
                ('cp', models.IntegerField(blank=True, db_column='CP', null=True)),
                ('ville', models.TextField(blank=True, db_column='VILLE', null=True)),
                ('web', models.TextField(blank=True, db_column='WEB', null=True)),
                ('coordonnees_geo', models.TextField(blank=True, db_column='COORDONNEES', null=True)),
            ],
            options={
                'db_table': 'coworking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_line', models.IntegerField(blank=True, db_column='ID Line', null=True)),
                ('libelle_line', models.IntegerField(blank=True, db_column='Libelle Line', null=True)),
                ('libelle_station', models.TextField(blank=True, db_column='Libelle station', null=True)),
                ('point_geo', models.TextField(blank=True, db_column='Point GEO', null=True)),
                ('finish', models.IntegerField(blank=True, null=True)),
                ('commune_nom', models.TextField(blank=True, db_column='Commune nom', null=True)),
                ('commune_code_insee', models.IntegerField(blank=True, db_column='Commune code Insee', null=True)),
            ],
            options={
                'db_table': 'metro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parcs',
            fields=[
                ('typologie_d_espace_vert', models.TextField(blank=True, db_column="Typologie d'espace vert", null=True)),
                ('id', models.IntegerField(db_column='Identifiant espace vert', primary_key=True, serialize=False)),
                ('nom', models.TextField(blank=True, db_column='Nom de lespace vert', null=True)),
                ('categorie', models.TextField(blank=True, db_column='Categorie', null=True)),
                ('adresse', models.TextField(blank=True, db_column='Adresse', null=True)),
                ('code_postal', models.IntegerField(blank=True, db_column='Code postal', null=True)),
                ('ouverture_24h_24h', models.TextField(blank=True, db_column='Ouverture 24h_24h', null=True)),
                ('coordonnees_geo', models.TextField(blank=True, db_column='Geo point', null=True)),
                ('presence_cloture', models.TextField(blank=True, db_column='Presence cloture', null=True)),
            ],
            options={
                'db_table': 'parcs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, db_column='Nom', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('cuisine', models.TextField(blank=True, db_column='Cuisine', null=True)),
                ('vegetarien', models.TextField(blank=True, db_column='Vegetarien', null=True)),
                ('vegane', models.TextField(blank=True, db_column='Vegane', null=True)),
                ('heures_ouverture', models.TextField(blank=True, db_column='Heures_ouverture', null=True)),
                ('acces_handicapes', models.TextField(blank=True, db_column='Acces_Handicapes', null=True)),
                ('telephone', models.TextField(blank=True, db_column='Telephone', null=True)),
                ('site_web', models.TextField(blank=True, db_column='Site_Web', null=True)),
                ('commune', models.TextField(blank=True, db_column='Commune', null=True)),
                ('code_commune', models.IntegerField(blank=True, db_column='Code_Commune', null=True)),
                ('departement', models.TextField(blank=True, db_column='Departement', null=True)),
                ('coordonnees_geo', models.TextField(blank=True, db_column='OSM_Point', null=True)),
                ('osm_url', models.TextField(blank=True, db_column='OSM_URL', null=True)),
            ],
            options={
                'db_table': 'resto',
                'managed': False,
            },
        ),
    ]
